Your friend has a coffee shop. They track sales data as follows:
- sales in a './data/coffee-shop-sales.csv' 
- prices and unit costs in './data/coffee-shop-prices.csv'
- each line in the sales spreadsheet represents the sale of a single item

Load the data and explore what's there. 
1. see the count of each item sold for each day.
2. most sold item
3. least sold item

In [2]:
# import pandas 
import pandas as pd

In [6]:
# read the files with the store data 
sales = pd.read_csv("./data/coffee-shop-sales.csv")
prices = pd.read_csv("./data/coffee-shop-prices.csv")

In [12]:
# add column for number of items sold in each sale, set it to 1. 
# This information is implied, but it will be helpful to make it more epxlicit 

sales["SaleQuantity"] = 1

In [13]:
# the count of each item sold for each day.
sale_item_groups = sales.groupby(['Date','Item'])
sale_item_groups.count()

                           SaleQuantity
Date    Item
8/10/22 Banana                        2
        Cookies                       3
        Ground Coffee                 1
        Muffin                        1
8/2/22  Banana                        1
        Chocolate Bar                 1
        Cookies                       3
        Ground Coffee                 1
        Muffin                        2
8/3/22  Banana                        1
        Cookies                       2
        Ground Coffee                 1
        Muffin                        2
        Whole Bean Coffee             1
8/4/22  Banana                        1
        Cookies                       2
        Ground Coffee                 1
        Muffin                        3
        Whole Bean Coffee             1
8/5/22  Banana                        1
        Chocolate Bar                 1
        Cookies                       2
        Ground Coffee                 2
        Muffin                        3
        Whole Bean Coffee             2
8/6/22  Banana                        1
        Chocolate Bar                 2
        Cookies                       3
        Muffin                        2
        Whole Bean Coffee             2
8/7/22  Banana                        2
        Chocolate Bar                 2
        Cookies                       4
        Ground Coffee                 1
        Muffin                        2
        Mug                           1
        Whole Bean Coffee             1
8/8/22  Banana                        2
        Chocolate Bar                 2
        Cookies                       4
        Ground Coffee                 2
        Muffin                        2
        Whole Bean Coffee             1
8/9/22  Banana                        2
        Cookies                       4
        Ground Coffee                 4
        Muffin                        2
        Mug                           1

In [16]:
# most sold item 
item_groups = sales.groupby(['Item'])
item_groups.count()

                   Date  SaleQuantity
Item
Banana               13            13
Chocolate Bar         8             8
Cookies              27            27
Ground Coffee        13            13
Muffin               19            19
Mug                   2             2
Whole Bean Coffee     8             8


They want to know:
- what is the most popular item
- what item they make the most profit on
- what item is the least popular
- how many of each item was sold total 
- how many of each item was sold per day, on average